# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.8
yarn_build=1
loader_version=0.17.2

# Mod Properties
mod_version=1.17.6
maven_group=net.mcbrawls
mod_id=blueprint

# Dependencies
fabric_version=0.132.0+1.21.8

kotlin_version=2.2.0
fabric_kotlin_version=1.13.4

codex_version=1.2
slate_version=1.0.3+1.21.6
fantasy_version=0.6.7+1.21.5
polymer_version=0.13.11+1.21.8
