# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.3
yarn_build=2
loader_version=0.16.7

# Mod Properties
mod_version=1.13
maven_group=net.mcbrawls
mod_id=blueprint

# Dependencies
fabric_version=0.107.0+1.21.3

kotlin_version=2.0.21
fabric_kotlin_version=1.12.3+kotlin.2.0.21

codex_version=1.5.0
sgui_version=1.7.2+1.21.2
fantasy_version=0.6.5+1.21.2
polymer_version=0.10.1+1.21.3
